### ISSUE TITLE
Difference in `parse` and `search`

### ISSUE THREAD

**Issue by timofurrer** [r1chardj0n3s/parse#41] opened 2017-05-06 15:12 UTC
I know that `parse.search` should be used to match a pattern at any position in the string whereas `parse.parse` has to match the string exactly.

The following issue came up some days ago in the radish project: https://github.com/radish-bdd/radish/issues/106
Especially this comment might be interesting: https://github.com/radish-bdd/radish/issues/106#issuecomment-299503624

> However, this gives as interesting outcome:
>  ```python
> >>> patt = parse.compile('I have a {}')
> >>> patt.search('I have a apple')
> <Result ('a',) {}>
> >>> patt.parse('I have a apple')
> <Result ('apple',) {}>
> ```
>
> and
>
 > ```python
> >>> patt = parse.compile('I {} a {}')
> >>> patt.parse('I have a apple')
> <Result ('have', 'apple') {}>
> >>> patt.search('I have a apple')
> <Result ('have', 'a') {}>
> ```

As you can see `search` and `parse` are giving different results. In this example it indeed be possible to just use `parse` - but in a lot of cases we use this library for is not.

Is this intended behavior?

*Adding @rscrimojr*

**Comment by r1chardj0n3s** [comment] 2017-05-07 01:24
That final patt.search() result does look buggy to me.

**Comment by timofurrer** [comment] 2017-05-07 08:41
Any idea what the problem could be?

**Comment by r1chardj0n3s** [comment] 2017-05-07 08:49
I've not had a chance to investigate.

**Comment by a-johnston** [comment] 2017-11-16 07:34
If this is still an issue, this is caused by https://github.com/r1chardj0n3s/parse/blob/master/parse.py#L871 since the group `(.+?)` matches lazily as opposed to `(.+)`. The reason parse works but search fails is that `_match_re` adds `$` to the end for parse, so the lazy match has to expand to the full string. However this does mean that search has totally broken/unexpected behavior for any patterns ending in a group.

It could be an easy fix just to remove the lazy `?` but I'm not familiar enough with the expected behavior to say that wouldn't break other things.

**Comment by r1chardj0n3s** [comment] 2017-12-14 02:12
The lazy match is often necessary so parse will match the minimum necessary to match the string. In hindsight, saying that the example provided is buggy was incorrect of me - it's doing exactly what was requested (ambiguously) of it. The library has no way to know how long the second element should be when *searching* through a text for a match (where the text could be very long indeed). I think I'm going to close this because there's really no action I believe I can take.

**Closed by r1chardj0n3s** 2017-12-14 02:12 UTC
